name: DEPLOY TO PRODUCTION

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Configuration
        uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --token "$FIREBASE_TOKEN"
          env:
            FIREBASE_TOKEN: ${{ secrets.firebaseDeploy }}
      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        env:
          API_KEY: ${{ secrets.pushNotification }}
          MESSAGE: "Tagee deploy on production"